### ISSUE TITLE
Receiving and passing on to a webservice?

### ISSUE THREAD

**Issue by chriso0710** [jctissier/whatsapp-assistant-bot#1]
Hi @jctissier,

I just found your project and it looks promising.

I once used https://github.com/tgalal/yowsup only for receiving Whatsapp messages. Until yowsup started to become too much of a struggle to keep it running and I abandoned it. I now think yowsup has too many problems and is dead.

I have been experimenting with WhatsappWeb, Selenium and Ruby for receiving Whatsapp messages, but found it not stable and quick enough.

Do you think, it would be possible to use/extent your project for receiving messages (with attachments) from multiple unknown contacts and simply passing them on to a webservice for processing? 

Thanks
Christian

**Comment by jctissier** [comment]
Hey chriso,

Yes it's definitely possible, you could just about make anything.

1. Receiving messages from multiple unknown contacts
You would need to add a function that would once in a while check if your bot has any unread messages. If you have any unread messages on web whatsapp, just inspect the chat without clicking it and find the element which stores the red bubble message with the number of unread messages.
[Example](https://i.imgur.com/nn8CigG.png)

2. Processing attachments
There are various types of attachments, easiest way to extract them is by using their CSS class names. Main examples:

    - picture attachment = "bubble-image"
         - parse the html and extract the blob:<url>
    - document attachment = "bubble bubble-doc"
         - parse the html and extract the base64 string for the PDF, there's python packages that will help you transform them into a file or just find a way to download it  

3. Passing them to a webservice
Definitely, just depends what you want to do but you can just call another script or function that will do what you want it to do

Hope that helps

**Comment by chriso0710** [comment]
Thank you very much for your detailed answer!

Did you take a look at 
https://github.com/mukulhase/WebWhatsAPI
before starting your project?

This looks good too and I am about to check WebWhatsAPI out. Apparently I will have to make two prototypes, using your approach and WebWhatsAPI to see what works best for me.

Just an idea: As both projects are using similar technologies (I like your approach with driving chrome somewhat better), maybe the projects could join/merge. I think WebWhatsAPI would need some help with attachments.

Christian

**Comment by jctissier** [comment]
I didn't but I just took a look and it looks interesting. 

From a quick glance at the repository, it looks like it's setup to help build custom bots and I do really like the ability of being able to bypass qr codes. However, WhatsApp has a pretty strong policy against making bots and I only made mine for personal use. 

Just depends what you want to do with your bot but using selenium, if you are only creating one or two bots to do a specific task for yourself, you can use my code and ask questions. It's not meant for large scale bot making/farming.

**Comment by gtcdevop** [comment]
@chriso0710 I've found a solution to send a file trough webWhatsapi. Mentioned in here
https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/370

I Hope this helps!!
