### ISSUE TITLE
The Bubble Tag is not Bubble anymore

### ISSUE THREAD

**Issue by juanse254** [jctissier/whatsapp-assistant-bot#2]
Aparently the Bubble Tag is not called bubble anymore, therefore

`def chat_history():
    text_bubbles = driver.find_elements_by_class_name("message-out")  # message-in = receiver, message-out = sender
    tmp_queue = []

    try:
        for bubble in text_bubbles:
            msg_texts = bubble.find_elements_by_class_name("copyable-text")
            for msg in msg_texts:
                #raw_msg_text = msg.find_element_by_class_name("selectable-text.invisible-space.copyable-text").text.lower()
                # raw_msg_time = msg.find_element_by_class_name("bubble-text-meta").text        # time message sent
                tmp_queue.append(msg.text.lower())

        if len(tmp_queue) > 0:
            return tmp_queue[-1]  # Send last message in list

    except StaleElementReferenceException as e:
        print(str(e))
        # Something went wrong, either keep polling until it comes back or figure out alternative

    return False`

Anyway, this is just the beginning as am getting "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"pluggable-input-body"}" so i guess classes have to be updated.

**Comment by juanse254** [comment]
I corrected the send method by this: `def send_message(msg):
    whatsapp_msg = driver.find_element_by_class_name('_2S1VP')
    whatsapp_msg.send_keys(msg)
    whatsapp_msg.send_keys(Keys.ENTER)`

Despite that, this fix might be incorrect. Will try to do it properly later and create pull req

**Comment by jctissier** [comment]
awesome, thanks for your help! Just merged your PR 👍
