### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by LGudi** [jctissier/whatsapp-assistant-bot#4]
hello I would like to help me with a question I have, I would like to find the contact id in whatsapp to which you are receiving the message or how to automate the message so as not to click on the contact

Thank you!. :)

**Comment by jctissier** [comment]
Hi LGudi,

Whatsapp Web does not provide a unique ID to each of your conversations. However, I will update my code next with how I am doing it. Remind me if I have not messaged you back.

**Comment by LGudi** [comment]
Thanks, I'll wait for your message to review the update.

**Comment by ItsRohan0165** [comment]
Hii LGudi,
Could you help me with this error, whenever i run the script i encounter this error


('/google bots', '14-05-28')
Command args: ['google', 'bots']
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="main"]/header/div[3]/div/div[2]/span/div/div/ul/li[1]/input"}
(Session info: chrome=73.0.3683.86)
(Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17134 x86_64)

('bot failed to retrieve search content, try again...', '14-05-42')

**Comment by jctissier** [comment]
@mark104478 Issues should be fixed now
